Vagrant.configure("2") do |config|

	config.vm.define "controller" do |controller|
		controller.vm.box = "ubuntu/bionic64"	
		controller.vm.hostname = "controller"		
		controller.vm.network "private_network", ip: "192.168.33.220"
		controller.vm.provider "virtualbox" do |vb|
			vb.gui = false
			vb.memory = 2048
			vb.cpus = 2
			vb.name = "controller"
		end
		controller.vm.provision "shell", path: "provision.sh"
		controller.vm.synced_folder 'shared', '/home/shared'
	end
		
	# Iterating the loop for two times
	(1..2).each do |i|
		# Defining VM properties
		 config.vm.define "ubuntu_#{i}" do |node|
            node.vm.box = "ubuntu/bionic64"	
			node.vm.hostname = "ubuntu#{i}"		
			node.vm.network "private_network", ip: "192.168.33.22#{i}"
            node.vm.provider "virtualbox" do |vb|
				vb.gui = false
				vb.memory = 1024
				vb.cpus = 1				
				vb.name = "controlled_ubuntu_#{i}"
            end
		end
	end
	
	config.vm.define "centos" do |centos|
		centos.vm.box = "generic/centos7"	
		centos.vm.hostname = "centos"		
		centos.vm.box_check_update = false
		centos.vm.network "private_network", ip: "192.168.33.223"
		centos.vm.provider "virtualbox" do |vb|
			vb.gui = false
			vb.memory = 1024
			vb.cpus = 1			
			vb.name = "controlled_centos"
		end
	end
end